export const WS_CREATED_ORDERS_CONNECTION_START = 'WS_CREATED_ORDERS_CONNECTION_START';
export const WS_CREATED_ORDERS_CONNECTION_SUCCESS = 'WS_CREATED_ORDERS_CONNECTION_SUCCESS';
export const WS_CREATED_ORDERS_CONNECTION_ERROR = 'WS_CREATED_ORDERS_CONNECTION_ERROR';
export const WS_CREATED_ORDERS_CONNECTION_CLOSED = 'WS_CREATED_ORDERS_CONNECTION_CLOSED';
export const WS_CREATED_ORDERS_GET_MESSAGE = 'WS_CREATED_ORDERS_GET_MESSAGE';
export const WS_CREATED_ORDERS_SEND_MESSAGE = 'WS_CREATED_ORDERS_SEND_MESSAGE';